import { ProfileAvatar } from "@/components/ProfileAvatar";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { useIsMobile } from "@/hooks/useMobile";
import { trpc } from "@/lib/trpc";
import { CalendarDays, FileText, LayoutDashboard, LogOut, PanelLeft, Sparkles, Users } from "lucide-react";
import { CSSProperties, useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";
import { DashboardLayoutSkeleton } from "./DashboardLayoutSkeleton";
import { Button } from "./ui/button";

const tutorItems = [{ icon: LayoutDashboard, label: "Overview", path: "/dashboard/tutor" }, { icon: Users, label: "Students", path: "/dashboard/tutor" }, { icon: CalendarDays, label: "Schedule", path: "/dashboard/tutor" }, { icon: Sparkles, label: "AI studio", path: "/dashboard/tutor" }];
const studentItems = [{ icon: LayoutDashboard, label: "My overview", path: "/dashboard/student" }, { icon: CalendarDays, label: "Schedule", path: "/dashboard/student" }, { icon: FileText, label: "Lesson history", path: "/dashboard/student" }];
const SIDEBAR_WIDTH_KEY = "sidebar-width";
export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const [sidebarWidth, setSidebarWidth] = useState(() => { const saved = localStorage.getItem(SIDEBAR_WIDTH_KEY); return saved ? parseInt(saved, 10) : 260; });
  const { loading, user } = useAuth();
  useEffect(() => { localStorage.setItem(SIDEBAR_WIDTH_KEY, sidebarWidth.toString()); }, [sidebarWidth]);
  if (loading) return <DashboardLayoutSkeleton />;
  if (!user) return <div className="app-grid flex min-h-screen items-center justify-center px-5"><div className="glass flex w-full max-w-md flex-col items-center gap-6 rounded-[2rem] p-9 text-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#e0efe8] text-[#39705e]"><Sparkles className="h-6 w-6" /></div><div><h1 className="text-2xl font-extrabold tracking-[-.04em]">Sign in to continue</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your dashboard is private to your TutorFlow account.</p></div><Button onClick={() => startLogin()} className="w-full rounded-2xl bg-[#203a3a] py-6 font-bold text-white">Sign in securely</Button></div></div>;
  return <SidebarProvider style={{ "--sidebar-width": `${sidebarWidth}px` } as CSSProperties}><DashboardLayoutContent user={user} setSidebarWidth={setSidebarWidth}>{children}</DashboardLayoutContent></SidebarProvider>;
}
function DashboardLayoutContent({ children, user, setSidebarWidth }: { children: React.ReactNode; user: any; setSidebarWidth: (width: number) => void }) {
  const { logout } = useAuth(); const [location, setLocation] = useLocation(); const { state, toggleSidebar } = useSidebar(); const isCollapsed = state === "collapsed"; const [isResizing, setIsResizing] = useState(false); const sidebarRef = useRef<HTMLDivElement>(null); const isMobile = useIsMobile(); const { data: profile } = trpc.profile.me.useQuery(undefined, { enabled: Boolean(user) }); const isStudent = profile?.role === "student" || user?.role === "student" || user?.name?.toLowerCase().includes("student"); const menuItems = isStudent ? studentItems : tutorItems;
  useEffect(() => { if (profile?.role === "student" && location.startsWith("/dashboard/tutor")) setLocation("/dashboard/student"); if (profile?.role === "tutor" && location.startsWith("/dashboard/student")) setLocation("/dashboard/tutor"); }, [profile?.role, location, setLocation]);
  useEffect(() => { const move = (e: MouseEvent) => { if (!isResizing) return; const left = sidebarRef.current?.getBoundingClientRect().left ?? 0; const width = e.clientX - left; if (width >= 210 && width <= 380) setSidebarWidth(width); }; const up = () => setIsResizing(false); if (isResizing) { document.addEventListener("mousemove", move); document.addEventListener("mouseup", up); document.body.style.cursor = "col-resize"; } return () => { document.removeEventListener("mousemove", move); document.removeEventListener("mouseup", up); document.body.style.cursor = ""; }; }, [isResizing, setSidebarWidth]);
  return <><div ref={sidebarRef} className="relative"><Sidebar collapsible="icon" className="border-r-0 bg-[#eef0eb]"><SidebarHeader className="h-16 justify-center"><div className="flex w-full items-center gap-3 px-2"><button onClick={toggleSidebar} className="grid h-8 w-8 shrink-0 place-items-center rounded-lg hover:bg-white/70" aria-label="Toggle navigation"><PanelLeft className="h-4 w-4 text-slate-500" /></button>{!isCollapsed && <div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#203a3a] text-[#f4ead9]"><Sparkles className="h-3.5 w-3.5" /></span><span className="font-[Manrope] font-extrabold tracking-[-.04em]">tutor<span className="text-[#5b8d7b]">flow</span></span></div>}</div></SidebarHeader><SidebarContent><p className="px-4 pb-2 pt-4 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Workspace</p><SidebarMenu className="px-2">{menuItems.map(item => <SidebarMenuItem key={item.label}><SidebarMenuButton isActive={location === item.path} onClick={() => setLocation(item.path)} tooltip={item.label} className="h-10 font-medium"><item.icon className="h-4 w-4" /><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="p-3"><DropdownMenu><DropdownMenuTrigger asChild><button className="flex w-full items-center gap-3 rounded-xl px-1 py-1 text-left hover:bg-white/70"><ProfileAvatar name={profile?.fullName || user?.name || "TutorFlow user"} avatarUrl={profile?.avatarUrl || user?.avatarUrl} className="h-9 w-9" /><div className="min-w-0 flex-1 group-data-[collapsible=icon]:hidden"><p className="truncate text-sm font-bold">{user?.name || "TutorFlow user"}</p><p className="mt-1 truncate text-xs text-slate-500">{user?.email || "Account"}</p></div></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48"><DropdownMenuItem onClick={logout} className="cursor-pointer text-destructive"><LogOut className="mr-2 h-4 w-4" />Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarFooter></Sidebar><div className={`absolute right-0 top-0 h-full w-1 cursor-col-resize hover:bg-[#5b8d7b]/20 ${isCollapsed ? "hidden" : ""}`} onMouseDown={() => setIsResizing(true)} /></div><SidebarInset>{isMobile && <div className="sticky top-0 z-40 flex h-14 items-center border-b bg-[#f5f4ef]/90 px-2 backdrop-blur"><SidebarTrigger className="h-9 w-9 rounded-lg bg-white/70" /><span className="ml-2 text-sm font-bold">{menuItems.find(i => i.path === location)?.label || "Workspace"}</span></div>}<main className="flex-1">{children}</main></SidebarInset></>;
}
